import { BcOrderCost } from './order_cost';
import { BcOrderProduct } from './order_product';

export class BcOrder implements Identifiable, DateTrackable, BcOrderCost {
    id: number;
    date_created: string;
    date_modified: string;
    subtotal_ex_tax: string;
    subtotal_inc_tax: string;
    subtotal_tax: string;
    base_shipping_cost: string;
    shipping_cost_ex_tax: string;
    shipping_cost_inc_tax: string;
    shipping_cost_tax: string;
    shipping_cost_tax_class_id: string;
    base_handling_cost: string;
    handling_cost_ex_tax: string;
    handling_cost_inc_tax: string;
    handling_cost_tax: string;
    handling_cost_tax_class_id: string;
    base_wrapping_cost: string;
    wrapping_cost_ex_tax: string;
    wrapping_cost_inc_tax: string;
    wrapping_cost_tax: string;
    wrapping_cost_tax_class_id: string;
    total_ex_tax: string;
    total_inc_tax: string;
    total_tax: string;
    coupon_discount: string;
    discount_amount: string;
    store_credit_amount: string;
    gift_certificate_amount: string;
    refunded_amount: string;
    customer_id: number;
    date_shipped: string;
    status_id: number;
    status: string;
    items_total: number;
    items_shipped: number;
    payment_method: string;
    payment_provider_id: string;
    payment_status: string;
    order_is_digital: boolean;
    ip_address: string;
    currency_id: number;
    currency_code: string;
    currency_exchange_rate: number;
    default_currency_id: number;
    default_currency_code: string;
    staff_notes: string;
    customer_message: string;
    is_deleted: boolean;
    external_id: string;
    external_source: string;
    channel_id: number;
    tax_provider_id: number;
    products?: Array<BcOrderProduct>;
}
