import { BcProduct } from '../shared/product';
import { AppliedDiscount } from './applied_discount';
import { BcOrderProductCost } from './order_product_cost';
import { ProductOption } from './product_option';

export class BcOrderProduct implements BcProduct, BcOrderProductCost {
    base_cost_price: string;
    cost_price_inc_tax: string;
    cost_price_ex_tax: string;
    cost_price_tax: string;
    base_price: string;
    price_ex_tax: string;
    price_inc_tax: string;
    price_tax: string;
    base_total: string;
    total_ex_tax: string;
    total_inc_tax: string;
    total_tax: string;
    refund_amount: string;
    base_wrapping_cost: string;
    wrapping_cost_ex_tax: string;
    wrapping_cost_inc_tax: string;
    wrapping_cost_tax: string;
    fixed_shipping_cost: string;
    id: number;
    name: string;
    type: string;
    sku: string;
    weight: number;
    upc: string;
    bin_picking_number: string;
    order_id: number;
    product_id: number;
    order_address_id: number;
    name_customer?: string;
    name_merchant?: string;
    quantity: number;
    is_refunded: boolean;
    quantity_refunded: number;
    return_id: number;
    wrapping_name: string;
    wrapping_message: string;
    quantity_shipped: number;
    ebay_item_id: string;
    ebay_transaction_id: string;
    option_set_id?: number;
    parent_order_product_id?: number;
    is_bundled_product: boolean;
    external_id: any;
    fulfillment_source: string;
    brand: string;
    applied_discounts: AppliedDiscount[];
    product_options: ProductOption[];
    configurable_fields: any[];
    gift_certificate_id: any;
    event_name: any;
    event_date: any;
}
