import { BcBaseQueryOptions } from '../base_query_options';

export class BcProductsRequestQuery extends BcBaseQueryOptions {
    id?: number;
    'id:in'?: string;
    'id:not_in'?: string;
    'id:min'?: string;
    'id:max'?: string;
    'id:greater'?: string;
    'id:less'?: string;
    name?: string;
    upc?: string;
    price?: number;
    weight?: number;
    condition?: string;
    brand_id?: number;
    date_modified?: string;
    'date_modified:max'?: string;
    'date_modified:min'?: string;
    date_last_imported?: string;
    'date_last_imported:max'?: string;
    'date_last_imported:min'?: string;
    is_visible?: boolean;
    is_featured?: number;
    is_free_shipping?: number;
    inventory_level?: number;
    'inventory_level:in'?: string;
    'inventory_level:not_in'?: string;
    'inventory_level:min'?: string;
    'inventory_level:max'?: string;
    'inventory_level:greater'?: string;
    'inventory_level:less'?: string;
    inventory_low?: number;
    out_of_stock?: number;
    total_sold?: number;
    type?: string;
    categories?: number;
    keyword?: string;
    keyword_context?: string;
    status?: number;
    include?: string;
    include_fields?: string;
    exclude_fields?: string;
    availability?: string;
    direction?: 'asc' | 'desc';
    'categories:in'?: string;
    sku?: string;
    'sku:in'?: string;
}
